server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
  auth:
    enabled: false
    secret: "Basic c2VjcmV0OmtleQ=="

data:
  local_ingestion:
    enabled: ${LOCAL_INGESTION_ENABLED:false}
    allow_ingest_from: ["*"]
  local_data_folder: local_data/private_gpt

ui:
  enabled: false
  path: /

# This configuration allows you to use GPU for creating embeddings while avoiding loading LLM into vRAM
llm:
  mode: mock

embedding:
  mode: mock

vectorstore:
  database: qdrant

nodestore:
  database: simple

qdrant:
  path: local_data/private_gpt/qdrant
